const colors = {
    primary: '#FBBA00',
    disabledButton: '#F5C754',
    disabledButtonSecondary: '#DEDEDE',
    secondary: '#ffffff',
    darkBackground: '#000000',
    darkBackgroundOpacity: 'rgba(0,0,0, 0.79)',
    lightBackground: '#F1F1F1',
    greyBorderColor: '#D4DBE8',
    codeFieldBorderColor: '#bababa',
    inputFormBackground: '#FCFCFC',
    subtextColor: '#8F8E8E',
    placeholderTextColor: '#939393',
    thirdColor: '#405473',
    badGraph: '#E43B3B',
    goodGraph: '#00bf63',
    trainingBackground: '#121212',
    mainTextColor: '#101010',
    titleTextColor: '#141c24',
    subtitleTextColor: '#6D6D6D',
    secondaryTextColor: '#8F8E8E',
    lightTextColor: '#ffffff',
    greyTextColor: '#CCC7C7',
    inputTextColor: '#fbfbfb',
    showoffTextColor: '#5E17EB',
    errorColor: '#EC5454',
};

export default colors;
